### ISSUE TITLE
unsubscribers not getting updated in campaign stats as hard or soft bounce  

### ISSUE THREAD

**Issue by sameerrocks** [magicdude4eva/port25-bouncehandler#15]
Hello Buddy,

the emails Unsubscribed in Lists and don't show up in Campaign Stats. also is there any way to get them in campaign Bounce section..

from bouncehandler.php 

    $Mailwizz_bounceRecord = array(
      $MailWizzType_bounceType,                     // 1-bounce-type (hard, soft, internal)
      $bounceRecord[PORT25_OFFSET_BOUNCE_JOBID],    // 2- Campaign-UID
      $bounceRecord[PORT25_OFFSET_BOUNCE_DSNSTATUS] // 3- bounce-reason
      );

this $bounceRecord[PORT25_OFFSET_BOUNCE_JOBID] always has NULL value comes from powermta bounce log and hence the code ahead written for hard and soft bounce sagrigation based on Campaign-UID doesnt work at all

please help to get solution to this issue

thanks

**Comment by magicdude4eva** [comment]
Please provide a full Port25 bounce-record where it shows that the job-id is NULL. If the job-id is always NULL, then it is a misconfiguration in MailWizz (or an older version which does not support this).

I suggest looking at the bounce-record in the Port25 accounting file to cross-check. It is also intentional that if a bounce-category can not be matched or if it is NULL, that the bounce is always hard. If your requirement is different, feel free to fork/change.

I will not have the time over the next 2 weeks to debug issues (in all honesty, 90 % of the issues raised are either related to an outdated version of MailWizz, Port25 and not reading READ.ME entirely as it covers those issues).

**Comment by sameerrocks** [comment]
Hello Buddy,

below is the bounce file content


type | timeQueued | bounceCat | vmta | orig | rcpt | srcMta | dlvSourceIp | jobId | dsnStatus | dsnMta | dsnDiag
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
b | 2017-10-10 14:15:01+0200 | bad-domain | pmta-vmta1 | bounce@domain.com | dieterbeschnidt@gasdas23sdfdgmx.net | domain.com (0.0.0.0) | 0.0.0.0 |   | 5.1.2 (bad destination system: no   such domain)

I am using PowerMTA™ 4.0r6 ...mailwizz 1.4.3

**Comment by masharif46** [comment]
@sameerrocks  PowerMTA™ 4.0r6  maybe not working . but you can try .......... i can give solution if want .contact with me. Thanks

**Comment by magicdude4eva** [comment]
Pretty much this: https://github.com/magicdude4eva/port25-bouncehandler#important-before-logging-issues
